# Generated by Django 4.1.1 on 2023-07-22 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreAlbum', models.CharField(max_length=100)),
                ('anioPublicacion', models.CharField(max_length=5)),
                ('fotoAlbum', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('estadoAlbum', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Disquera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nitDisquera', models.CharField(max_length=25)),
                ('nombreDisquera', models.CharField(max_length=100)),
                ('telefonoDisquera', models.CharField(max_length=15)),
                ('direccionDisquera', models.CharField(max_length=100)),
                ('estadoDisquera', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreGenero', models.CharField(max_length=50)),
                ('estadoGenero', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCancion', models.CharField(max_length=100)),
                ('duracionCancion', models.IntegerField()),
                ('estadoCancion', models.BooleanField()),
                ('idAlbumFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disqueradc.album')),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('noDocumento', models.CharField(max_length=20)),
                ('tipoDocumento', models.CharField(max_length=20)),
                ('nombreArtista', models.CharField(max_length=50)),
                ('apellidoArtista', models.CharField(max_length=50)),
                ('nombreArtistico', models.CharField(max_length=50)),
                ('fNacimArtista', models.DateField(blank=True, null=True)),
                ('emailArtista', models.CharField(max_length=100)),
                ('fotoArtista', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('estadoArtista', models.BooleanField()),
                ('idDisqueraFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disqueradc.disquera')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='idArtistaFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disqueradc.artista'),
        ),
        migrations.AddField(
            model_name='album',
            name='idGeneroFk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disqueradc.genero'),
        ),
    ]
